

[paths]
bin_archive = 'D:\data\astro\ratan-600\sun\fast_acquisition\1-3ghz\bin'
fits_archive = 'D:\data\astro\ratan-600\sun\fast_acquisition\1-3ghz\fits'
#fits_sun_archive
#fits_sources_archive

# Настройки логирования
[logging]
log_path = 'D:\data\bin2fits_fast_acq_1_3ghz\logs'
failed_bin_files_log = 'D:\data\bin2fits_fast_acq_1_3ghz\logs\failed_bin_files.log'
log_level = "DEBUG"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
console_output = true
log_format = '%(asctime)s [%(levelname)s] %(message)s'
date_format = '%Y-%m-%d %H:%M:%S'
rotation_size_mb = 10
backup_count = 5

[[logging.handlers]]
level = "DEBUG"
filename = "debug.log"

[[logging.handlers]]
level = "INFO"
filename = "info.log"

[[logging.handlers]]
level = "WARNING"
filename = "warning.log"

[[logging.handlers]]
level = "ERROR"
filename = "error.log"

[[logging.handlers]]
level = "CRITICAL"
filename = "critical.log"